package com.patrones.software.creaciones.builder;
/*
 * SEPARA LA CONSTRUCCION DE OBJETOS COMPLEJOS, 
 * DE SU REPRESENTACION , 
 * PARA QUE EL MISMO PROCESO DE CONSTRUCCION 
 * PUEDA CREAR REPRESENTACIONES DIFERENTES.
 
  
  
  
  EL PROBLEMA DE LA CREACION DE CONSTRUCTORES CON GRAN CANTIDAD DE PARAMETROS SE 
  LO CONOCE COMO TELESCOPING CONSTRUCTOR
  
  PASO 1: CREAR UN CONSTRUCTOR QUE RECIBA COMO PARAMETROS
  LOS VALORES MINIMOS NECESARIOS (OBLIGATORIOS) PARA CREAR EL OBJETO
  
  PASO 2: COLOCAR ESTE CONSTRUCTOR COMO PRIVADO 
  
  PASO 3 ES CREAR LOS SETTERS DE LOS ATRIBUTOS OPCIONALES
  CON LA MODIFICACION DE QUE AHORA CADA SETTER RETORNE EL MISMO OBJETO
  
  PASO 4: GENERAR UN NUEVO METODO QUE RETORNE EL OBJETO FINAL, 
  POR CONVENCION LO LLAMAREMOS BUILD
 */
