package com.patrones.software.builder;

/*
 * RESOLVER LA SIGUIENTE PROBLEMÁTICA EN CLASE
 * 
 
VAMOS A AGREGAR 2 ATRIBUTOS METODO DE PAGO Y UN ATRIBUTO TOKEN


LA REGLA DE NEGOCIO SON: 
UNICAMENTE VAMOS A PODER ASIGNAR UN VALOR AL ATRIBUTO METODO DE PAGO 
CUANDO EMAIL, TELEFONO, DIRECCION, TENGAN UN VALOR, 

SI Y SOLO SI LOS 3 ATRIBUTOS TENGAN VALOR.
UNA VEZ ASIGNEMOS UN METODO DE PAGO, 
PUEDE SER TARJETA CREDITO, DEBTO, PAYPAL, 
SE VA A HABILITAR LA OPCION DE PODER ASIGNAR UN TOKEN

 */
