package com.patrones.software.creacionales.abstractfactory;
/*
 * EL ABSTRACT FACTORY NOS PROVEE DE UNA INTERFAZ, 
 * PARA CREAR FAMILIA DE OBJETOS RELACIONADOS O DEPENDIENTES.
SIN ESPECIFICAR SU CLASE EN CONCRETO.


DENTRO DE LA INTERFAZ VAMOS A PODER DEFINIR N CANTIDAD DE METODOS
LOS CUALES NOS PERMITIRAN CREAR OBJETOS

EN EL FACTORY METHOD, NOSOTROS UNICAMENTE UTILIZAMOS UNO,
EN EL ABTSRACT FACTORY NOSOTROS VAMOS A DEFINIR N, LOS QUE NECESITEMOS

TAREA: AGREGAR ATRIBUTOS A OBJETOS DE RETORNO
		IMPRIMIR EL OBJETO QUE DEVUELVE LA FABRICA

 */
