package com.patrones.software.estructurales.adapter;

/*
 * CONVIERTE LA INTERFAZ DE UNA CLASE EN OTRA INTERFAZ, 
 * QUE EL CLIENTE ESPERA
 * 
 * CON ADAPTER NOSOTROS PODEMOS HACER QUE CLASES QUE NO
 *  TRABAJAN EN CONJUNTO (POR ESTRUCTRA, ETC ) LO LOGREN
 * 
 * ES BASTANTE UTIL CUANDO QUEREMOS EXTENDER NUESTRA APLICACION
 * 
 * LO IMPORTANTE DE EXTENDER NUESTRA APLICACION ES QUE 
 * LO LOGRUEMOS SIN NECESIDAD DE HACER CAMBIOS EXTREMOS
 *  A NUESTRO CLIENTE
 * 
 * EJEMPLO: VAMOS A SIMULAR QUE NOS CONECTAMOS A UNA BASE DE DATOS Y REALIZAMOS UNA CONSULTA
 * 
 */